2022-12-26 09:38:34.485683: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-26 09:38:34.687628: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-26 09:38:49.297073: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib64:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/mpfr-4.1.0-4owr5jskgrebkppacvwkfa7tdtlqjalg/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/gmp-6.2.1-rg3gv5myy7lt46cjxvmdmsghhyhxguqo/lib:/work/FAC/FBM/DMF/smartin/cellfusion/wanlan/miniconda3/envs/tf210/lib/
2022-12-26 09:38:49.297219: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib64:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gcc-10.4.0-7fjdev7tbifqfonsjwlqmr6qcnza2ezu/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/mpfr-4.1.0-4owr5jskgrebkppacvwkfa7tdtlqjalg/lib:/dcsrsoft/spack/arolle/v1.0/spack/opt/spack/linux-rhel8-zen2/gcc-10.4.0/gmp-6.2.1-rg3gv5myy7lt46cjxvmdmsghhyhxguqo/lib:/work/FAC/FBM/DMF/smartin/cellfusion/wanlan/miniconda3/envs/tf210/lib/
2022-12-26 09:38:49.297231: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-12-26 09:39:12.407432: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-26 09:39:13.416855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38224 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:21:00.0, compute capability: 8.0
2022-12-26 09:39:13.418922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38224 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:e2:00.0, compute capability: 8.0
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I1226 09:39:13.800504 140238928709248 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
I1226 09:39:13.808058 140238928709248 deeplab.py:58] Synchronized Batchnorm is used.
I1226 09:39:13.808773 140238928709248 axial_resnet_instances.py:144] Axial-ResNet final config: {'num_blocks': [3, 6, 3, 3], 'backbone_layer_multiplier': 4.5, 'width_multiplier': 1, 'stem_width_multiplier': 1, 'output_stride': 16, 'classification_mode': True, 'backbone_type': 'wider_resnet', 'use_axial_beyond_stride': 16, 'backbone_use_transformer_beyond_stride': 0, 'extra_decoder_use_transformer_beyond_stride': 32, 'backbone_decoder_num_stacks': 0, 'backbone_decoder_blocks_per_stage': 1, 'extra_decoder_num_stacks': 0, 'extra_decoder_blocks_per_stage': 1, 'max_num_mask_slots': 128, 'num_mask_slots': 128, 'memory_channels': 256, 'base_transformer_expansion': 1.0, 'global_feed_forward_network_channels': 256, 'high_resolution_output_stride': 4, 'activation': 'relu', 'block_group_config': {'attention_bottleneck_expansion': 4, 'drop_path_keep_prob': 0.8, 'drop_path_beyond_stride': 4, 'drop_path_schedule': 'linear', 'positional_encoding_type': None, 'use_global_beyond_stride': 0, 'use_sac_beyond_stride': 0, 'use_squeeze_and_excite': False, 'conv_use_recompute_grad': True, 'axial_use_recompute_grad': True, 'recompute_within_stride': 0, 'transformer_use_recompute_grad': False, 'axial_layer_config': {'query_shape': (129, 129), 'key_expansion': 2, 'value_expansion': 4, 'memory_flange': (32, 32), 'double_global_attention': False, 'num_heads': 8, 'use_query_rpe_similarity': True, 'use_key_rpe_similarity': True, 'use_content_similarity': True, 'retrieve_value_rpe': True, 'retrieve_value_content': True, 'initialization_std_for_query_key_rpe': 1.0, 'initialization_std_for_value_rpe': 1.0, 'self_attention_activation': 'softmax'}, 'dual_path_transformer_layer_config': {'num_heads': 8, 'bottleneck_expansion': 2, 'key_expansion': 1, 'value_expansion': 2, 'feed_forward_network_channels': 2048, 'use_memory_self_attention': True, 'use_pixel2memory_feedback_attention': True, 'transformer_activation': 'softmax'}}, 'bn_layer': functools.partial(<class 'keras.layers.normalization.batch_normalization.SyncBatchNormalization'>, momentum=0.99, epsilon=0.001), 'conv_kernel_weight_decay': 0.0}
I1226 09:39:14.262028 140238928709248 deeplab.py:99] Setting pooling size to (33, 33)
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.487019 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.489814 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.491693 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.492308 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.494624 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.495236 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.496782 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.497333 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.499585 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.500178 140238928709248 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
I1226 09:39:18.517717 140238928709248 controller.py:391] restoring or initializing model...
I1226 09:39:18.907204 140238928709248 controller.py:395] restored model from ../model_dir/ckpt-40000.
I1226 09:39:18.907372 140238928709248 controller.py:217] restored from checkpoint: ../model_dir/ckpt-40000
I1226 09:39:18.907581 140238928709248 controller.py:236] train | step:  40000 | training until step 60000...
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:21.014802 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:21.186271 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:21.200643 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:22.657231 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:22.672353 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:22.687064 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:23.234307 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:23.249048 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:23.263436 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
INFO:tensorflow:batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
I1226 09:39:23.365982 140238928709248 cross_device_ops.py:897] batch_all_reduce: 1 all-reduces with algorithm = nccl, num_packs = 1
2022-12-26 09:49:39.722552: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
2022-12-26 09:49:39.746122: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8401
2022-12-26 09:49:49.757893: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-12-26 09:49:50.908016: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
W1226 10:02:57.212305 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 40000, expected updated value to be 40100, but it was 40200.
I1226 10:02:57.233933 140238928709248 controller.py:457] train | step:  40200 | steps/sec:    0.1 | output: 
    {'learning_rate': 2.7651826e-05,
     'losses/train_center_loss': 0.07429316,
     'losses/train_regression_loss': 1.0251937,
     'losses/train_semantic_loss': 1.6622262,
     'losses/train_total_loss': 2.7617126}
W1226 10:15:39.700626 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 40200, expected updated value to be 40300, but it was 40400.
I1226 10:15:39.701677 140238928709248 controller.py:457] train | step:  40400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.740032e-05,
     'losses/train_center_loss': 0.071910664,
     'losses/train_regression_loss': 1.0149256,
     'losses/train_semantic_loss': 1.6506253,
     'losses/train_total_loss': 2.7374613}
W1226 10:28:27.260583 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 40400, expected updated value to be 40500, but it was 40600.
I1226 10:28:27.261596 140238928709248 controller.py:457] train | step:  40600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.7148555e-05,
     'losses/train_center_loss': 0.071824096,
     'losses/train_regression_loss': 1.0046431,
     'losses/train_semantic_loss': 1.6272058,
     'losses/train_total_loss': 2.7036736}
W1226 10:41:12.137329 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 40600, expected updated value to be 40700, but it was 40800.
I1226 10:41:12.138336 140238928709248 controller.py:457] train | step:  40800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.6896529e-05,
     'losses/train_center_loss': 0.07213292,
     'losses/train_regression_loss': 1.002037,
     'losses/train_semantic_loss': 1.6280295,
     'losses/train_total_loss': 2.7021997}
W1226 10:53:56.655344 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 40800, expected updated value to be 40900, but it was 41000.
I1226 10:53:56.656389 140238928709248 controller.py:457] train | step:  41000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.6644244e-05,
     'losses/train_center_loss': 0.071076125,
     'losses/train_regression_loss': 0.9961114,
     'losses/train_semantic_loss': 1.6249871,
     'losses/train_total_loss': 2.6921747}
I1226 10:54:05.730054 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-41000.
W1226 11:06:51.658208 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 41000, expected updated value to be 41100, but it was 41200.
I1226 11:06:51.659068 140238928709248 controller.py:457] train | step:  41200 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.639169e-05,
     'losses/train_center_loss': 0.07090197,
     'losses/train_regression_loss': 0.99298906,
     'losses/train_semantic_loss': 1.6282644,
     'losses/train_total_loss': 2.6921558}
W1226 11:19:34.888805 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 41200, expected updated value to be 41300, but it was 41400.
I1226 11:19:34.890233 140238928709248 controller.py:457] train | step:  41400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.6138869e-05,
     'losses/train_center_loss': 0.0693866,
     'losses/train_regression_loss': 0.9837549,
     'losses/train_semantic_loss': 1.6284928,
     'losses/train_total_loss': 2.6816344}
W1226 11:32:20.486013 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 41400, expected updated value to be 41500, but it was 41600.
I1226 11:32:20.486846 140238928709248 controller.py:457] train | step:  41600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.5885776e-05,
     'losses/train_center_loss': 0.06811152,
     'losses/train_regression_loss': 0.9817676,
     'losses/train_semantic_loss': 1.6143051,
     'losses/train_total_loss': 2.6641839}
W1226 11:45:07.774739 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 41600, expected updated value to be 41700, but it was 41800.
I1226 11:45:07.775746 140238928709248 controller.py:457] train | step:  41800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.563241e-05,
     'losses/train_center_loss': 0.06847718,
     'losses/train_regression_loss': 0.97487116,
     'losses/train_semantic_loss': 1.623006,
     'losses/train_total_loss': 2.6663537}
W1226 11:58:04.684782 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 41800, expected updated value to be 41900, but it was 42000.
I1226 11:58:04.685631 140238928709248 controller.py:457] train | step:  42000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.537876e-05,
     'losses/train_center_loss': 0.06886258,
     'losses/train_regression_loss': 0.97699034,
     'losses/train_semantic_loss': 1.6192378,
     'losses/train_total_loss': 2.665091}
I1226 11:58:12.797460 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-42000.
W1226 12:10:57.305349 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 42000, expected updated value to be 42100, but it was 42200.
I1226 12:10:57.306358 140238928709248 controller.py:457] train | step:  42200 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.5124831e-05,
     'losses/train_center_loss': 0.06766831,
     'losses/train_regression_loss': 0.97835374,
     'losses/train_semantic_loss': 1.6087979,
     'losses/train_total_loss': 2.6548204}
W1226 12:23:42.623027 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 42200, expected updated value to be 42300, but it was 42400.
I1226 12:23:42.623865 140238928709248 controller.py:457] train | step:  42400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.4870616e-05,
     'losses/train_center_loss': 0.06985977,
     'losses/train_regression_loss': 0.9727329,
     'losses/train_semantic_loss': 1.6213417,
     'losses/train_total_loss': 2.663935}
W1226 12:36:21.986997 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 42400, expected updated value to be 42500, but it was 42600.
I1226 12:36:21.987867 140238928709248 controller.py:457] train | step:  42600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.4616118e-05,
     'losses/train_center_loss': 0.070237495,
     'losses/train_regression_loss': 0.98182946,
     'losses/train_semantic_loss': 1.6217548,
     'losses/train_total_loss': 2.6738214}
W1226 12:49:12.324501 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 42600, expected updated value to be 42700, but it was 42800.
I1226 12:49:12.325339 140238928709248 controller.py:457] train | step:  42800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.436132e-05,
     'losses/train_center_loss': 0.06589114,
     'losses/train_regression_loss': 0.96971166,
     'losses/train_semantic_loss': 1.6102514,
     'losses/train_total_loss': 2.6458545}
W1226 13:01:58.212945 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 42800, expected updated value to be 42900, but it was 43000.
I1226 13:01:58.213957 140238928709248 controller.py:457] train | step:  43000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.4106224e-05,
     'losses/train_center_loss': 0.06856881,
     'losses/train_regression_loss': 0.97884446,
     'losses/train_semantic_loss': 1.6196659,
     'losses/train_total_loss': 2.6670794}
I1226 13:02:05.859318 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-43000.
W1226 13:14:50.446812 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 43000, expected updated value to be 43100, but it was 43200.
I1226 13:14:50.490528 140238928709248 controller.py:457] train | step:  43200 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.385083e-05,
     'losses/train_center_loss': 0.06869203,
     'losses/train_regression_loss': 0.9769077,
     'losses/train_semantic_loss': 1.6191049,
     'losses/train_total_loss': 2.6647043}
W1226 13:27:36.346759 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 43200, expected updated value to be 43300, but it was 43400.
I1226 13:27:36.347578 140238928709248 controller.py:457] train | step:  43400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.3595132e-05,
     'losses/train_center_loss': 0.068296105,
     'losses/train_regression_loss': 0.9748256,
     'losses/train_semantic_loss': 1.6125528,
     'losses/train_total_loss': 2.6556747}
W1226 13:40:22.982526 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 43400, expected updated value to be 43500, but it was 43600.
I1226 13:40:22.983394 140238928709248 controller.py:457] train | step:  43600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.3339124e-05,
     'losses/train_center_loss': 0.06844433,
     'losses/train_regression_loss': 0.97354156,
     'losses/train_semantic_loss': 1.621036,
     'losses/train_total_loss': 2.663022}
W1226 13:53:07.955586 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 43600, expected updated value to be 43700, but it was 43800.
I1226 13:53:07.956462 140238928709248 controller.py:457] train | step:  43800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.3082808e-05,
     'losses/train_center_loss': 0.06692579,
     'losses/train_regression_loss': 0.9698314,
     'losses/train_semantic_loss': 1.6063839,
     'losses/train_total_loss': 2.6431406}
W1226 14:05:54.361624 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 43800, expected updated value to be 43900, but it was 44000.
I1226 14:05:54.362597 140238928709248 controller.py:457] train | step:  44000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.2826176e-05,
     'losses/train_center_loss': 0.06812878,
     'losses/train_regression_loss': 0.97064424,
     'losses/train_semantic_loss': 1.614636,
     'losses/train_total_loss': 2.6534088}
I1226 14:06:02.436515 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-44000.
W1226 14:18:43.537551 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 44000, expected updated value to be 44100, but it was 44200.
I1226 14:18:43.538373 140238928709248 controller.py:457] train | step:  44200 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.256922e-05,
     'losses/train_center_loss': 0.06769674,
     'losses/train_regression_loss': 0.96368486,
     'losses/train_semantic_loss': 1.6003833,
     'losses/train_total_loss': 2.6317654}
W1226 14:31:25.213137 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 44200, expected updated value to be 44300, but it was 44400.
I1226 14:31:25.213997 140238928709248 controller.py:457] train | step:  44400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.2311937e-05,
     'losses/train_center_loss': 0.067485444,
     'losses/train_regression_loss': 0.96195143,
     'losses/train_semantic_loss': 1.6177475,
     'losses/train_total_loss': 2.6471841}
W1226 14:44:09.010941 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 44400, expected updated value to be 44500, but it was 44600.
I1226 14:44:09.011800 140238928709248 controller.py:457] train | step:  44600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.2054326e-05,
     'losses/train_center_loss': 0.066316806,
     'losses/train_regression_loss': 0.956165,
     'losses/train_semantic_loss': 1.5926986,
     'losses/train_total_loss': 2.61518}
W1226 14:56:53.031156 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 44600, expected updated value to be 44700, but it was 44800.
I1226 14:56:53.032017 140238928709248 controller.py:457] train | step:  44800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.1796382e-05,
     'losses/train_center_loss': 0.068445876,
     'losses/train_regression_loss': 0.9719707,
     'losses/train_semantic_loss': 1.622184,
     'losses/train_total_loss': 2.6626008}
W1226 15:09:39.761596 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 44800, expected updated value to be 44900, but it was 45000.
I1226 15:09:39.762422 140238928709248 controller.py:457] train | step:  45000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.1538097e-05,
     'losses/train_center_loss': 0.06617639,
     'losses/train_regression_loss': 0.9632092,
     'losses/train_semantic_loss': 1.6001745,
     'losses/train_total_loss': 2.6295605}
I1226 15:09:47.564837 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-45000.
W1226 15:22:30.657596 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 45000, expected updated value to be 45100, but it was 45200.
I1226 15:22:30.658595 140238928709248 controller.py:457] train | step:  45200 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.1279466e-05,
     'losses/train_center_loss': 0.0639347,
     'losses/train_regression_loss': 0.9536301,
     'losses/train_semantic_loss': 1.5911965,
     'losses/train_total_loss': 2.6087613}
W1226 15:35:07.539142 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 45200, expected updated value to be 45300, but it was 45400.
I1226 15:35:07.539964 140238928709248 controller.py:457] train | step:  45400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.1020487e-05,
     'losses/train_center_loss': 0.06690386,
     'losses/train_regression_loss': 0.9616158,
     'losses/train_semantic_loss': 1.6094575,
     'losses/train_total_loss': 2.6379766}
W1226 15:47:49.123389 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 45400, expected updated value to be 45500, but it was 45600.
I1226 15:47:49.124219 140238928709248 controller.py:457] train | step:  45600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.0761152e-05,
     'losses/train_center_loss': 0.06779924,
     'losses/train_regression_loss': 0.9645854,
     'losses/train_semantic_loss': 1.607576,
     'losses/train_total_loss': 2.6399603}
W1226 16:00:26.312413 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 45600, expected updated value to be 45700, but it was 45800.
I1226 16:00:26.313248 140238928709248 controller.py:457] train | step:  45800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.0501455e-05,
     'losses/train_center_loss': 0.06817131,
     'losses/train_regression_loss': 0.96143264,
     'losses/train_semantic_loss': 1.5868553,
     'losses/train_total_loss': 2.6164594}
W1226 16:13:14.206406 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 45800, expected updated value to be 45900, but it was 46000.
I1226 16:13:14.207231 140238928709248 controller.py:457] train | step:  46000 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.0241394e-05,
     'losses/train_center_loss': 0.06860254,
     'losses/train_regression_loss': 0.96026087,
     'losses/train_semantic_loss': 1.5879632,
     'losses/train_total_loss': 2.616827}
I1226 16:13:23.132874 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-46000.
W1226 16:26:06.040752 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 46000, expected updated value to be 46100, but it was 46200.
I1226 16:26:06.041613 140238928709248 controller.py:457] train | step:  46200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.998096e-05,
     'losses/train_center_loss': 0.06522319,
     'losses/train_regression_loss': 0.9532664,
     'losses/train_semantic_loss': 1.5880073,
     'losses/train_total_loss': 2.6064973}
W1226 16:38:54.397849 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 46200, expected updated value to be 46300, but it was 46400.
I1226 16:38:54.398688 140238928709248 controller.py:457] train | step:  46400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.9720152e-05,
     'losses/train_center_loss': 0.06720178,
     'losses/train_regression_loss': 0.9593629,
     'losses/train_semantic_loss': 1.5996813,
     'losses/train_total_loss': 2.626246}
W1226 16:51:36.363630 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 46400, expected updated value to be 46500, but it was 46600.
I1226 16:51:36.364597 140238928709248 controller.py:457] train | step:  46600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.9458956e-05,
     'losses/train_center_loss': 0.065570064,
     'losses/train_regression_loss': 0.9494762,
     'losses/train_semantic_loss': 1.6001681,
     'losses/train_total_loss': 2.6152143}
W1226 17:04:20.801928 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 46600, expected updated value to be 46700, but it was 46800.
I1226 17:04:20.802767 140238928709248 controller.py:457] train | step:  46800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.9197369e-05,
     'losses/train_center_loss': 0.06619258,
     'losses/train_regression_loss': 0.9527746,
     'losses/train_semantic_loss': 1.5984973,
     'losses/train_total_loss': 2.6174643}
W1226 17:17:07.276780 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 46800, expected updated value to be 46900, but it was 47000.
I1226 17:17:07.277652 140238928709248 controller.py:457] train | step:  47000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.8935387e-05,
     'losses/train_center_loss': 0.06628661,
     'losses/train_regression_loss': 0.9643711,
     'losses/train_semantic_loss': 1.5853904,
     'losses/train_total_loss': 2.6160479}
I1226 17:17:15.490236 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-47000.
W1226 17:30:01.366533 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 47000, expected updated value to be 47100, but it was 47200.
I1226 17:30:01.367378 140238928709248 controller.py:457] train | step:  47200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.8673e-05,
     'losses/train_center_loss': 0.064316064,
     'losses/train_regression_loss': 0.95421845,
     'losses/train_semantic_loss': 1.5930408,
     'losses/train_total_loss': 2.6115746}
W1226 17:42:42.571372 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 47200, expected updated value to be 47300, but it was 47400.
I1226 17:42:42.572220 140238928709248 controller.py:457] train | step:  47400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.8410205e-05,
     'losses/train_center_loss': 0.06520381,
     'losses/train_regression_loss': 0.95625734,
     'losses/train_semantic_loss': 1.6039453,
     'losses/train_total_loss': 2.6254065}
W1226 17:55:34.425358 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 47400, expected updated value to be 47500, but it was 47600.
I1226 17:55:34.426222 140238928709248 controller.py:457] train | step:  47600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.8146991e-05,
     'losses/train_center_loss': 0.06615166,
     'losses/train_regression_loss': 0.9512343,
     'losses/train_semantic_loss': 1.6013806,
     'losses/train_total_loss': 2.6187668}
W1226 18:08:18.480712 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 47600, expected updated value to be 47700, but it was 47800.
I1226 18:08:18.498877 140238928709248 controller.py:457] train | step:  47800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.7883354e-05,
     'losses/train_center_loss': 0.0645165,
     'losses/train_regression_loss': 0.94916093,
     'losses/train_semantic_loss': 1.5826383,
     'losses/train_total_loss': 2.5963159}
W1226 18:21:05.940235 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 47800, expected updated value to be 47900, but it was 48000.
I1226 18:21:05.941070 140238928709248 controller.py:457] train | step:  48000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.7619283e-05,
     'losses/train_center_loss': 0.06583674,
     'losses/train_regression_loss': 0.94208246,
     'losses/train_semantic_loss': 1.5945221,
     'losses/train_total_loss': 2.6024406}
I1226 18:21:14.203107 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-48000.
W1226 18:33:53.531056 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 48000, expected updated value to be 48100, but it was 48200.
I1226 18:33:53.531873 140238928709248 controller.py:457] train | step:  48200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.7354772e-05,
     'losses/train_center_loss': 0.06521078,
     'losses/train_regression_loss': 0.9527967,
     'losses/train_semantic_loss': 1.6030432,
     'losses/train_total_loss': 2.621051}
W1226 18:46:40.569347 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 48200, expected updated value to be 48300, but it was 48400.
I1226 18:46:40.570199 140238928709248 controller.py:457] train | step:  48400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.7089815e-05,
     'losses/train_center_loss': 0.06319052,
     'losses/train_regression_loss': 0.94573015,
     'losses/train_semantic_loss': 1.5956,
     'losses/train_total_loss': 2.6045208}
W1226 18:59:31.689988 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 48400, expected updated value to be 48500, but it was 48600.
I1226 18:59:31.690873 140238928709248 controller.py:457] train | step:  48600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.6824397e-05,
     'losses/train_center_loss': 0.06367506,
     'losses/train_regression_loss': 0.93362486,
     'losses/train_semantic_loss': 1.5763812,
     'losses/train_total_loss': 2.573681}
W1226 19:12:11.650687 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 48600, expected updated value to be 48700, but it was 48800.
I1226 19:12:11.651897 140238928709248 controller.py:457] train | step:  48800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.6558515e-05,
     'losses/train_center_loss': 0.06387929,
     'losses/train_regression_loss': 0.93967956,
     'losses/train_semantic_loss': 1.582481,
     'losses/train_total_loss': 2.58604}
W1226 19:25:01.212657 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 48800, expected updated value to be 48900, but it was 49000.
I1226 19:25:01.213522 140238928709248 controller.py:457] train | step:  49000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.6292157e-05,
     'losses/train_center_loss': 0.065743685,
     'losses/train_regression_loss': 0.9423248,
     'losses/train_semantic_loss': 1.6046264,
     'losses/train_total_loss': 2.612695}
I1226 19:25:09.325019 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-49000.
W1226 19:37:55.778509 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 49000, expected updated value to be 49100, but it was 49200.
I1226 19:37:55.779490 140238928709248 controller.py:457] train | step:  49200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.6025315e-05,
     'losses/train_center_loss': 0.064901866,
     'losses/train_regression_loss': 0.9465521,
     'losses/train_semantic_loss': 1.5884926,
     'losses/train_total_loss': 2.5999465}
W1226 19:50:39.630423 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 49200, expected updated value to be 49300, but it was 49400.
I1226 19:50:39.631257 140238928709248 controller.py:457] train | step:  49400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.5757976e-05,
     'losses/train_center_loss': 0.06458649,
     'losses/train_regression_loss': 0.94138414,
     'losses/train_semantic_loss': 1.5782455,
     'losses/train_total_loss': 2.5842164}
W1226 20:03:27.442497 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 49400, expected updated value to be 49500, but it was 49600.
I1226 20:03:27.443336 140238928709248 controller.py:457] train | step:  49600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.5490137e-05,
     'losses/train_center_loss': 0.063991636,
     'losses/train_regression_loss': 0.9323772,
     'losses/train_semantic_loss': 1.5790085,
     'losses/train_total_loss': 2.5753772}
W1226 20:16:07.327925 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 49600, expected updated value to be 49700, but it was 49800.
I1226 20:16:07.328806 140238928709248 controller.py:457] train | step:  49800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.5221779e-05,
     'losses/train_center_loss': 0.06339996,
     'losses/train_regression_loss': 0.9413741,
     'losses/train_semantic_loss': 1.6012858,
     'losses/train_total_loss': 2.6060598}
W1226 20:28:48.381547 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 49800, expected updated value to be 49900, but it was 50000.
I1226 20:28:48.382396 140238928709248 controller.py:457] train | step:  50000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.4952892e-05,
     'losses/train_center_loss': 0.06318136,
     'losses/train_regression_loss': 0.9498417,
     'losses/train_semantic_loss': 1.5778764,
     'losses/train_total_loss': 2.5908997}
I1226 20:28:56.564155 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-50000.
W1226 20:41:45.263747 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 50000, expected updated value to be 50100, but it was 50200.
I1226 20:41:45.264564 140238928709248 controller.py:457] train | step:  50200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.468347e-05,
     'losses/train_center_loss': 0.06541246,
     'losses/train_regression_loss': 0.9531969,
     'losses/train_semantic_loss': 1.5691282,
     'losses/train_total_loss': 2.5877368}
W1226 20:54:23.157862 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 50200, expected updated value to be 50300, but it was 50400.
I1226 20:54:23.158683 140238928709248 controller.py:457] train | step:  50400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.44134965e-05,
     'losses/train_center_loss': 0.064413846,
     'losses/train_regression_loss': 0.94606584,
     'losses/train_semantic_loss': 1.610264,
     'losses/train_total_loss': 2.620744}
W1226 21:07:16.004653 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 50400, expected updated value to be 50500, but it was 50600.
I1226 21:07:16.005515 140238928709248 controller.py:457] train | step:  50600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.414296e-05,
     'losses/train_center_loss': 0.06498086,
     'losses/train_regression_loss': 0.93795455,
     'losses/train_semantic_loss': 1.5591282,
     'losses/train_total_loss': 2.562064}
W1226 21:20:04.261556 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 50600, expected updated value to be 50700, but it was 50800.
I1226 21:20:04.262550 140238928709248 controller.py:457] train | step:  50800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.3871842e-05,
     'losses/train_center_loss': 0.06376981,
     'losses/train_regression_loss': 0.9394178,
     'losses/train_semantic_loss': 1.5862665,
     'losses/train_total_loss': 2.5894532}
W1226 21:32:40.752718 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 50800, expected updated value to be 50900, but it was 51000.
I1226 21:32:40.753606 140238928709248 controller.py:457] train | step:  51000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.3600139e-05,
     'losses/train_center_loss': 0.06359045,
     'losses/train_regression_loss': 0.93333226,
     'losses/train_semantic_loss': 1.5706818,
     'losses/train_total_loss': 2.567604}
I1226 21:32:48.803422 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-51000.
W1226 21:45:38.563097 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 51000, expected updated value to be 51100, but it was 51200.
I1226 21:45:38.563946 140238928709248 controller.py:457] train | step:  51200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.3327831e-05,
     'losses/train_center_loss': 0.06466678,
     'losses/train_regression_loss': 0.938785,
     'losses/train_semantic_loss': 1.5822028,
     'losses/train_total_loss': 2.5856545}
W1226 21:58:31.129605 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 51200, expected updated value to be 51300, but it was 51400.
I1226 21:58:31.130442 140238928709248 controller.py:457] train | step:  51400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.3054905e-05,
     'losses/train_center_loss': 0.06385484,
     'losses/train_regression_loss': 0.93914396,
     'losses/train_semantic_loss': 1.5737485,
     'losses/train_total_loss': 2.5767474}
W1226 22:11:11.528857 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 51400, expected updated value to be 51500, but it was 51600.
I1226 22:11:11.529691 140238928709248 controller.py:457] train | step:  51600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.2781344e-05,
     'losses/train_center_loss': 0.065121114,
     'losses/train_regression_loss': 0.9382434,
     'losses/train_semantic_loss': 1.5818913,
     'losses/train_total_loss': 2.5852556}
W1226 22:23:55.190446 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 51600, expected updated value to be 51700, but it was 51800.
I1226 22:23:55.191287 140238928709248 controller.py:457] train | step:  51800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.2507127e-05,
     'losses/train_center_loss': 0.0617281,
     'losses/train_regression_loss': 0.92951065,
     'losses/train_semantic_loss': 1.5849231,
     'losses/train_total_loss': 2.5761614}
W1226 22:36:38.043741 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 51800, expected updated value to be 51900, but it was 52000.
I1226 22:36:38.044744 140238928709248 controller.py:457] train | step:  52000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.2232243e-05,
     'losses/train_center_loss': 0.060526766,
     'losses/train_regression_loss': 0.93486327,
     'losses/train_semantic_loss': 1.5640875,
     'losses/train_total_loss': 2.5594778}
I1226 22:36:46.066156 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-52000.
W1226 22:49:34.505619 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 52000, expected updated value to be 52100, but it was 52200.
I1226 22:49:34.506494 140238928709248 controller.py:457] train | step:  52200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.1956671e-05,
     'losses/train_center_loss': 0.06254372,
     'losses/train_regression_loss': 0.9353815,
     'losses/train_semantic_loss': 1.5726188,
     'losses/train_total_loss': 2.5705442}
W1226 23:02:25.363532 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 52200, expected updated value to be 52300, but it was 52400.
I1226 23:02:25.364407 140238928709248 controller.py:457] train | step:  52400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.168039e-05,
     'losses/train_center_loss': 0.06252617,
     'losses/train_regression_loss': 0.92855316,
     'losses/train_semantic_loss': 1.5767124,
     'losses/train_total_loss': 2.5677912}
W1226 23:15:03.937573 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 52400, expected updated value to be 52500, but it was 52600.
I1226 23:15:03.938424 140238928709248 controller.py:457] train | step:  52600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.1403383e-05,
     'losses/train_center_loss': 0.062420305,
     'losses/train_regression_loss': 0.9404602,
     'losses/train_semantic_loss': 1.574018,
     'losses/train_total_loss': 2.5768988}
W1226 23:27:53.930536 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 52600, expected updated value to be 52700, but it was 52800.
I1226 23:27:53.931366 140238928709248 controller.py:457] train | step:  52800 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.1125627e-05,
     'losses/train_center_loss': 0.061888713,
     'losses/train_regression_loss': 0.94131696,
     'losses/train_semantic_loss': 1.5752077,
     'losses/train_total_loss': 2.5784135}
W1226 23:40:35.748241 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 52800, expected updated value to be 52900, but it was 53000.
I1226 23:40:35.749102 140238928709248 controller.py:457] train | step:  53000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.0847095e-05,
     'losses/train_center_loss': 0.06422724,
     'losses/train_regression_loss': 0.93899643,
     'losses/train_semantic_loss': 1.5857327,
     'losses/train_total_loss': 2.5889564}
I1226 23:40:44.220618 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-53000.
W1226 23:53:31.282303 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 53000, expected updated value to be 53100, but it was 53200.
I1226 23:53:31.283152 140238928709248 controller.py:457] train | step:  53200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.0567767e-05,
     'losses/train_center_loss': 0.062186398,
     'losses/train_regression_loss': 0.9258439,
     'losses/train_semantic_loss': 1.5575691,
     'losses/train_total_loss': 2.545599}
W1227 00:06:23.449633 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 53200, expected updated value to be 53300, but it was 53400.
I1227 00:06:23.450643 140238928709248 controller.py:457] train | step:  53400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.02876165e-05,
     'losses/train_center_loss': 0.06127611,
     'losses/train_regression_loss': 0.9342877,
     'losses/train_semantic_loss': 1.5609201,
     'losses/train_total_loss': 2.556484}
W1227 00:19:06.913770 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 53400, expected updated value to be 53500, but it was 53600.
I1227 00:19:06.915786 140238928709248 controller.py:457] train | step:  53600 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.0006616e-05,
     'losses/train_center_loss': 0.063317224,
     'losses/train_regression_loss': 0.9311043,
     'losses/train_semantic_loss': 1.5636219,
     'losses/train_total_loss': 2.5580432}
W1227 00:31:55.898085 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 53600, expected updated value to be 53700, but it was 53800.
I1227 00:31:55.898965 140238928709248 controller.py:457] train | step:  53800 | steps/sec:    0.3 | output: 
    {'learning_rate': 9.724736e-06,
     'losses/train_center_loss': 0.06391313,
     'losses/train_regression_loss': 0.93960845,
     'losses/train_semantic_loss': 1.5848098,
     'losses/train_total_loss': 2.5883312}
W1227 00:44:35.375619 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 53800, expected updated value to be 53900, but it was 54000.
I1227 00:44:35.376474 140238928709248 controller.py:457] train | step:  54000 | steps/sec:    0.3 | output: 
    {'learning_rate': 9.441945e-06,
     'losses/train_center_loss': 0.062275626,
     'losses/train_regression_loss': 0.9346711,
     'losses/train_semantic_loss': 1.5920882,
     'losses/train_total_loss': 2.5890348}
I1227 00:44:43.321939 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-54000.
W1227 00:57:25.391541 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 54000, expected updated value to be 54100, but it was 54200.
I1227 00:57:25.392419 140238928709248 controller.py:457] train | step:  54200 | steps/sec:    0.3 | output: 
    {'learning_rate': 9.158206e-06,
     'losses/train_center_loss': 0.06412356,
     'losses/train_regression_loss': 0.93992066,
     'losses/train_semantic_loss': 1.5742822,
     'losses/train_total_loss': 2.5783262}
W1227 01:10:15.776662 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 54200, expected updated value to be 54300, but it was 54400.
I1227 01:10:15.777492 140238928709248 controller.py:457] train | step:  54400 | steps/sec:    0.3 | output: 
    {'learning_rate': 8.873487e-06,
     'losses/train_center_loss': 0.06342568,
     'losses/train_regression_loss': 0.9377569,
     'losses/train_semantic_loss': 1.5709891,
     'losses/train_total_loss': 2.5721712}
W1227 01:23:02.321396 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 54400, expected updated value to be 54500, but it was 54600.
I1227 01:23:02.322224 140238928709248 controller.py:457] train | step:  54600 | steps/sec:    0.3 | output: 
    {'learning_rate': 8.587751e-06,
     'losses/train_center_loss': 0.06391504,
     'losses/train_regression_loss': 0.92648864,
     'losses/train_semantic_loss': 1.5689594,
     'losses/train_total_loss': 2.5593634}
W1227 01:35:43.328191 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 54600, expected updated value to be 54700, but it was 54800.
I1227 01:35:43.329038 140238928709248 controller.py:457] train | step:  54800 | steps/sec:    0.3 | output: 
    {'learning_rate': 8.300955e-06,
     'losses/train_center_loss': 0.06099715,
     'losses/train_regression_loss': 0.9286009,
     'losses/train_semantic_loss': 1.580743,
     'losses/train_total_loss': 2.570341}
W1227 01:48:32.668587 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 54800, expected updated value to be 54900, but it was 55000.
I1227 01:48:32.669450 140238928709248 controller.py:457] train | step:  55000 | steps/sec:    0.3 | output: 
    {'learning_rate': 8.013055e-06,
     'losses/train_center_loss': 0.0600282,
     'losses/train_regression_loss': 0.92531985,
     'losses/train_semantic_loss': 1.574464,
     'losses/train_total_loss': 2.5598118}
I1227 01:48:40.915390 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-55000.
W1227 02:01:27.684427 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 55000, expected updated value to be 55100, but it was 55200.
I1227 02:01:27.685401 140238928709248 controller.py:457] train | step:  55200 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.723998e-06,
     'losses/train_center_loss': 0.062069856,
     'losses/train_regression_loss': 0.93830764,
     'losses/train_semantic_loss': 1.5683175,
     'losses/train_total_loss': 2.5686948}
W1227 02:14:10.376756 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 55200, expected updated value to be 55300, but it was 55400.
I1227 02:14:10.390664 140238928709248 controller.py:457] train | step:  55400 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.433737e-06,
     'losses/train_center_loss': 0.062120706,
     'losses/train_regression_loss': 0.92538613,
     'losses/train_semantic_loss': 1.5828143,
     'losses/train_total_loss': 2.5703213}
W1227 02:26:55.570178 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 55400, expected updated value to be 55500, but it was 55600.
I1227 02:26:55.571050 140238928709248 controller.py:457] train | step:  55600 | steps/sec:    0.3 | output: 
    {'learning_rate': 7.1422082e-06,
     'losses/train_center_loss': 0.06374006,
     'losses/train_regression_loss': 0.9250647,
     'losses/train_semantic_loss': 1.5649446,
     'losses/train_total_loss': 2.5537498}
W1227 02:39:37.167234 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 55600, expected updated value to be 55700, but it was 55800.
I1227 02:39:37.168066 140238928709248 controller.py:457] train | step:  55800 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.8493514e-06,
     'losses/train_center_loss': 0.0627384,
     'losses/train_regression_loss': 0.9305075,
     'losses/train_semantic_loss': 1.5585449,
     'losses/train_total_loss': 2.5517907}
W1227 02:52:19.086024 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 55800, expected updated value to be 55900, but it was 56000.
I1227 02:52:19.086884 140238928709248 controller.py:457] train | step:  56000 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.555097e-06,
     'losses/train_center_loss': 0.061369866,
     'losses/train_regression_loss': 0.91644174,
     'losses/train_semantic_loss': 1.5524285,
     'losses/train_total_loss': 2.53024}
I1227 02:52:30.637787 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-56000.
W1227 03:05:17.440542 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 56000, expected updated value to be 56100, but it was 56200.
I1227 03:05:17.441377 140238928709248 controller.py:457] train | step:  56200 | steps/sec:    0.3 | output: 
    {'learning_rate': 6.259367e-06,
     'losses/train_center_loss': 0.06160452,
     'losses/train_regression_loss': 0.9340685,
     'losses/train_semantic_loss': 1.5802276,
     'losses/train_total_loss': 2.5759003}
W1227 03:18:00.631685 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 56200, expected updated value to be 56300, but it was 56400.
I1227 03:18:00.632547 140238928709248 controller.py:457] train | step:  56400 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.962076e-06,
     'losses/train_center_loss': 0.062602445,
     'losses/train_regression_loss': 0.93950903,
     'losses/train_semantic_loss': 1.5904672,
     'losses/train_total_loss': 2.5925786}
W1227 03:30:42.947884 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 56400, expected updated value to be 56500, but it was 56600.
I1227 03:30:42.948894 140238928709248 controller.py:457] train | step:  56600 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.6631266e-06,
     'losses/train_center_loss': 0.062462512,
     'losses/train_regression_loss': 0.9307648,
     'losses/train_semantic_loss': 1.5622824,
     'losses/train_total_loss': 2.5555096}
W1227 03:43:22.318033 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 56600, expected updated value to be 56700, but it was 56800.
I1227 03:43:22.318856 140238928709248 controller.py:457] train | step:  56800 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.3624126e-06,
     'losses/train_center_loss': 0.061923914,
     'losses/train_regression_loss': 0.926594,
     'losses/train_semantic_loss': 1.5682105,
     'losses/train_total_loss': 2.5567286}
W1227 03:56:02.116311 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 56800, expected updated value to be 56900, but it was 57000.
I1227 03:56:02.117177 140238928709248 controller.py:457] train | step:  57000 | steps/sec:    0.3 | output: 
    {'learning_rate': 5.0598132e-06,
     'losses/train_center_loss': 0.06127346,
     'losses/train_regression_loss': 0.9122285,
     'losses/train_semantic_loss': 1.5566893,
     'losses/train_total_loss': 2.5301914}
I1227 03:56:10.502631 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-57000.
W1227 04:08:51.339604 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 57000, expected updated value to be 57100, but it was 57200.
I1227 04:08:51.340450 140238928709248 controller.py:457] train | step:  57200 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.755186e-06,
     'losses/train_center_loss': 0.061634615,
     'losses/train_regression_loss': 0.9304149,
     'losses/train_semantic_loss': 1.5798987,
     'losses/train_total_loss': 2.571948}
W1227 04:21:34.973319 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 57200, expected updated value to be 57300, but it was 57400.
I1227 04:21:34.974154 140238928709248 controller.py:457] train | step:  57400 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.448375e-06,
     'losses/train_center_loss': 0.063231915,
     'losses/train_regression_loss': 0.9204715,
     'losses/train_semantic_loss': 1.5653024,
     'losses/train_total_loss': 2.5490057}
W1227 04:34:20.964600 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 57400, expected updated value to be 57500, but it was 57600.
I1227 04:34:20.965420 140238928709248 controller.py:457] train | step:  57600 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.139191e-06,
     'losses/train_center_loss': 0.060381945,
     'losses/train_regression_loss': 0.9159752,
     'losses/train_semantic_loss': 1.5788611,
     'losses/train_total_loss': 2.5552182}
W1227 04:47:04.861395 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 57600, expected updated value to be 57700, but it was 57800.
I1227 04:47:04.862249 140238928709248 controller.py:457] train | step:  57800 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.827417e-06,
     'losses/train_center_loss': 0.05929411,
     'losses/train_regression_loss': 0.91133606,
     'losses/train_semantic_loss': 1.5561423,
     'losses/train_total_loss': 2.5267725}
W1227 04:59:50.379880 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 57800, expected updated value to be 57900, but it was 58000.
I1227 04:59:50.380838 140238928709248 controller.py:457] train | step:  58000 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.512792e-06,
     'losses/train_center_loss': 0.060239326,
     'losses/train_regression_loss': 0.91664916,
     'losses/train_semantic_loss': 1.554364,
     'losses/train_total_loss': 2.5312524}
I1227 04:59:58.578706 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-58000.
W1227 05:12:45.700769 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 58000, expected updated value to be 58100, but it was 58200.
I1227 05:12:45.701608 140238928709248 controller.py:457] train | step:  58200 | steps/sec:    0.3 | output: 
    {'learning_rate': 3.194994e-06,
     'losses/train_center_loss': 0.060337514,
     'losses/train_regression_loss': 0.91787493,
     'losses/train_semantic_loss': 1.5643829,
     'losses/train_total_loss': 2.5425951}
W1227 05:25:28.061871 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 58200, expected updated value to be 58300, but it was 58400.
I1227 05:25:28.062694 140238928709248 controller.py:457] train | step:  58400 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.8736426e-06,
     'losses/train_center_loss': 0.061636582,
     'losses/train_regression_loss': 0.9284976,
     'losses/train_semantic_loss': 1.5670569,
     'losses/train_total_loss': 2.5571907}
W1227 05:38:13.418542 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 58400, expected updated value to be 58500, but it was 58600.
I1227 05:38:13.419373 140238928709248 controller.py:457] train | step:  58600 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.5482382e-06,
     'losses/train_center_loss': 0.05987343,
     'losses/train_regression_loss': 0.9141469,
     'losses/train_semantic_loss': 1.5683151,
     'losses/train_total_loss': 2.5423357}
W1227 05:50:58.846196 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 58600, expected updated value to be 58700, but it was 58800.
I1227 05:50:58.847018 140238928709248 controller.py:457] train | step:  58800 | steps/sec:    0.3 | output: 
    {'learning_rate': 2.2181348e-06,
     'losses/train_center_loss': 0.059762087,
     'losses/train_regression_loss': 0.9157088,
     'losses/train_semantic_loss': 1.5518582,
     'losses/train_total_loss': 2.5273294}
W1227 06:03:41.397187 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 58800, expected updated value to be 58900, but it was 59000.
I1227 06:03:41.398030 140238928709248 controller.py:457] train | step:  59000 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.8824562e-06,
     'losses/train_center_loss': 0.06108863,
     'losses/train_regression_loss': 0.923257,
     'losses/train_semantic_loss': 1.5559283,
     'losses/train_total_loss': 2.5402741}
I1227 06:03:49.134701 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-59000.
W1227 06:16:27.444015 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 59000, expected updated value to be 59100, but it was 59200.
I1227 06:16:27.444849 140238928709248 controller.py:457] train | step:  59200 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.5399471e-06,
     'losses/train_center_loss': 0.061597537,
     'losses/train_regression_loss': 0.921503,
     'losses/train_semantic_loss': 1.5830008,
     'losses/train_total_loss': 2.566101}
W1227 06:29:09.892892 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 59200, expected updated value to be 59300, but it was 59400.
I1227 06:29:09.893855 140238928709248 controller.py:457] train | step:  59400 | steps/sec:    0.3 | output: 
    {'learning_rate': 1.1886689e-06,
     'losses/train_center_loss': 0.05992769,
     'losses/train_regression_loss': 0.91666883,
     'losses/train_semantic_loss': 1.5558928,
     'losses/train_total_loss': 2.5324893}
W1227 06:41:55.208044 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 59400, expected updated value to be 59500, but it was 59600.
I1227 06:41:55.208869 140238928709248 controller.py:457] train | step:  59600 | steps/sec:    0.3 | output: 
    {'learning_rate': 8.252372e-07,
     'losses/train_center_loss': 0.061368257,
     'losses/train_regression_loss': 0.92517745,
     'losses/train_semantic_loss': 1.5595893,
     'losses/train_total_loss': 2.5461352}
W1227 06:54:44.296627 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 59600, expected updated value to be 59700, but it was 59800.
I1227 06:54:44.297456 140238928709248 controller.py:457] train | step:  59800 | steps/sec:    0.3 | output: 
    {'learning_rate': 4.422338e-07,
     'losses/train_center_loss': 0.061694387,
     'losses/train_regression_loss': 0.91765285,
     'losses/train_semantic_loss': 1.5462896,
     'losses/train_total_loss': 2.525637}
W1227 07:07:23.609135 140238928709248 controller.py:448] `trainer.train(100)` did not update `global_step` by 100. Old value was 59800, expected updated value to be 59900, but it was 60000.
I1227 07:07:23.624330 140238928709248 controller.py:457] train | step:  60000 | steps/sec:    0.3 | output: 
    {'learning_rate': 0.0,
     'losses/train_center_loss': 0.060176592,
     'losses/train_regression_loss': 0.9174238,
     'losses/train_semantic_loss': 1.5614353,
     'losses/train_total_loss': 2.539036}
I1227 07:07:31.595498 140238928709248 controller.py:486] saved checkpoint to ../model_dir/ckpt-60000.
